#!/usr/bin/env bash
#setting up load balancing
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'frontend http
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 4826-web-01 3.91.201.135:80 check
        server 4826-web-02 18.215.171.156:80 check
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
